#!/usr/bin/env bash
# script that install lb named haproxy
apt-get update
apt-get -y install haproxy
echo "ENABLED=1" >> /etc/default/haproxy
sed -i '/504.http/a \\nlisten http-in\n\tbind *:80\n\tmode http\n\tbalance roundrobin\n\tserver 14374-web-01 3.236.225.249 check\n\tserver 14374-web-02 3.226.254.20 check' /etc/haproxy/haproxy.cfg
sudo service haproxy start
